# Generate the bucket we replicate from, and configure CRR between the two

Parameters:
  replicateToBucket:
    Description: Bucket to replicate to (in a different region)
    Type: String

Outputs:
  replicateFromBucket:
    Description: Bucket that S3 CRR will be setup on
    Value: !Ref 'replicateFromBucket'
    Export:
      Name: !Sub "${AWS::StackName}-bucket"

Resources:
  replicateFromBucket:
    Type: AWS::S3::Bucket
    Properties:
      ReplicationConfiguration:
        Role: !GetAtt [WorkItemBucketBackupRole, Arn]
        Rules:
        - Destination:
            Bucket: !Join ['', ['arn:aws:s3:::', !Ref 'replicateToBucket' ]]
            StorageClass: STANDARD
          Id: Backup
          Prefix: ''
          Status: Enabled
      VersioningConfiguration:
        Status: Enabled
  WorkItemBucketBackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [s3.amazonaws.com]
  BucketBackupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action: ['s3:GetReplicationConfiguration', 's3:ListBucket']
          Effect: Allow
          Resource:
          - !Join ['', ['arn:aws:s3:::', !Ref 'replicateFromBucket']]
        - Action: ['s3:GetObjectVersion', 's3:GetObjectVersionAcl']
          Effect: Allow
          Resource:
          - !Join ['', ['arn:aws:s3:::', !Ref 'replicateFromBucket', /*]]
        - Action: ['s3:ReplicateObject', 's3:ReplicateDelete']
          Effect: Allow
          Resource:
          - !Join ['', ['arn:aws:s3:::', !Ref 'replicateToBucket' , '/*']]
      PolicyName: BucketBackupPolicy
      Roles: [!Ref 'WorkItemBucketBackupRole']
