AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket to replicate to in CRR

Outputs:
  ReplicateToBucketName:
    Description: Bucket created by this stack that we will replicate to
    Value: !Ref 'replicateToBucket'

Resources:
  replicateToBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref 'AWS::AccountId', !Ref 'AWS::Region', 'replicate', 'to']]
      VersioningConfiguration:
        Status: Enabled